name: Linter check

on:
  - push
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
      - name: Run Makefile
        run: make lint
