name: make-master

on:
  - push
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - run: poetry --version
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make lint
